-- ===================================================================================
-- SCRIPT SETUP TABEL GRACELY NOTIFICATIONS
-- Ini akan membuat tabel baru bernama "gracely_notifications"
-- dan mengimpor semua pengumuman bawaan dari aturhonma.js secara instan!
-- Silakan jalankan script ini di SQL Editor Dasbor Supabase Anda.
-- ===================================================================================

-- 1. Buat Tabel
CREATE TABLE IF NOT EXISTS public.gracely_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL, -- 'announcement' atau 'folderInfo'
    key_id TEXT NOT NULL, -- contoh: 'info-html-nov-2025' atau 'chatgpt-group-id'
    html_content TEXT NOT NULL,
    is_enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Setup Keamanan (Row Level Security / RLS) agar bisa dibaca Ekstensi
ALTER TABLE public.gracely_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable Read Access for Public/Ext" 
ON public.gracely_notifications 
FOR SELECT 
USING (true);

-- 3. Impor Data Otomatis Bawaan dari aturhonma.js
-- (Gunakan klausa ON CONFLICT DO NOTHING jika Anda ingin mencegah masuknya data kembar jika script ini tak sengaja dijalankan 2x)
-- Agar mendukung ON CONFLICT, kita harus buat KEY unik.
ALTER TABLE public.gracely_notifications ADD CONSTRAINT unique_type_key UNIQUE (type, key_id);

INSERT INTO public.gracely_notifications (type, key_id, is_enabled, html_content)
VALUES 
-- [1] Impor GLOBAL ANNOUNCEMENT
(
    'announcement', 
    'info-html-nov-2025', 
    true, 
    '<div class=''notificationModal-content''><i class=''fa fa-times close-icon'' id=''notification-close''></i> <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Informasi</h2> <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''> <p style=''margin: 6px 0; font-size: 14px;''><b>Web Portal</b>: gracely011.github.io/hai/</p> <p style=''margin: 6px 0; font-size: 14px;''><b>My Blog</b>: petrussiahaan.blogspot.com</p> </div> <div style=''border: 2px dashed #666666; padding: 8px 10px; border-radius: 8px; background: #f5f5f5; margin-bottom: 12px;''> <p style=''margin: 0; text-align: center; color: #333333; font-size: 13px;''>Jika bukan TUHAN yang menolong aku,</p> <p style=''margin: 0; text-align: center; color: #333333; font-size: 13px;''>nyaris aku diam di tempat sunyi.</p> <p style=''margin: 0; text-align: center; color: #333333; font-size: 13px;''><b>Mazmur 94 : 17</b> 😊🙏</p> </div><button class=''ud-main-btn'' id=''notification-ok''>OK Lae</button></div>'
),

-- [2] Impor FOLDER INFO: ChatGPT
(
    'folderInfo', 
    'chatgpt-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>ChatGPT</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p style=''text-align: center;''><img src="https://us1.discourse-cdn.com/openai1/original/4X/7/0/1/701493b167007f5ab689eda8f388260e7390abc1.png" width="90%"></p>
                 <p style=''margin: 6px 0; font-size: 14px;''>Jika kamu mengalami pesan error: <b>"Something went wrong while generating the response"</b>, cukup hapus cookie dan cache pada browser yang kamu gunakan.</p>
                 <p style=''margin: 6px 0; font-size: 14px;''>Jika kamu mengalami pesan error: <b>"Detected unusual activity"</b>, silahkan gunakan akun lain atau gunakan alternatif seperti <b>Sider/NoteGPT/You/Merlin</b>.</p>
                 <p style=''margin: 6px 0; font-size: 14px;''>Jika model o1 sedang limit, kamu tetap dapat menggunakan model 4o.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [3] Impor FOLDER INFO: Freepik
(
    'folderInfo', 
    'freepik-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Informasi</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>Jika kamu ingin mengunduh file <b>.mv</b> atau <b>.mp4</b>, gunakan <b>Freepik 2-3</b></p>
                 <p><b>Freepik 1</b> (Server 1-10 digunakan untuk mengunduh tipe file jpg, png, tidak untuk mengunduh icon / video)</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [4] Impor FOLDER INFO: Canva
(
    'folderInfo', 
    'canva-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Informasi</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>Silakan undang email pribadi kamu untuk bergabung dengan team Canva. Jika sudah penuh, mohon laporkan melalui Telegram.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [5] Impor FOLDER INFO: ProCapCut
(
    'folderInfo', 
    'procapcut-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Informasi</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>CapCut pada Pro menggunakan CapCut Teams. Fitur Pro dapat dinikmati melalui manual login pada mobile &amp; desktop app CapCut.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [6] Impor FOLDER INFO: Canva Pro
(
    'folderInfo', 
    'canva-pro-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Informasi</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>Silakan undang email pribadi kamu untuk bergabung dengan team Canva. Jika sudah penuh, mohon laporkan melalui Telegram.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [7] Impor FOLDER INFO: Merlin AI
(
    'folderInfo', 
    'getmerlin.in-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Merlin AI</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p><b>22/01/2026</b> Merlin sudah diperbarui.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [8] Impor FOLDER INFO: Claude
(
    'folderInfo', 
    'claude-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Claude</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p><img src="https://i.ibb.co.com/Vptr5NxB/c613db4c-71ff-44f1-8110-797054a43f5e.jpg" width="90%"></p>
                 <p>Kamu tetap dapat melakukan akses ke Claude via Merlin AI [Diperbarui <b>22/01/2026</b>]</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok'' style=''background: #10a37f; color: white;''>Oke Lae</button>'
),

-- [9] Impor FOLDER INFO: Perplexity
(
    'folderInfo', 
    'perplexity-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Perplexity</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>Jika Perpexity <b>tidak terlogin-login</b>, silahkan lakukan akses ulang sampai terlogin.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [10] Impor FOLDER INFO: Gemini
(
    'folderInfo', 
    'gemini-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Gemini</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p><b>Please DO NOT attempt to log in using a mobile phone or tablet.</b> For security reasons, this account is only accessible via desktop or laptop web browsers.</p>
 <p><b>Mohon JANGAN mencoba masuk menggunakan ponsel atau tablet.</b> Demi alasan keamanan, akun ini hanya dapat diakses melalui browser web desktop atau laptop.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [11] Impor FOLDER INFO: WeTV
(
    'folderInfo', 
    'wetv-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>WeTV</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>Jika WeTV tidak VIP, silahkan tunggu 5 detik lalu lakukan refresh pada browser yang kamu gunakan.</p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
),

-- [12] Impor FOLDER INFO: Prime Video
(
    'folderInfo', 
    'prime-video-group-id', 
    true, 
    '<i class=''fa fa-times close-icon'' id=''notification-close''></i>
               <h2 style=''margin: 0 0 16px 0; text-align: center; color: #2c3e50; font-size: 22px; border-bottom: 3px solid #333333; padding-bottom: 8px;''>Info Prime Video</h2>
               <div style=''background: #f8f9fa; padding: 12px; border-radius: 8px; margin-bottom: 10px;''>
                 <p>Jika Prime Video meminta PIN, masukan <b>''12345''</b></p>
               </div>
               <button class=''ud-main-btn'' id=''notification-ok''>Oke Lae</button>'
)
ON CONFLICT (type, key_id) 
DO UPDATE SET html_content = EXCLUDED.html_content;

-- Selesai! Tabel siap digunakan Ekstensi.
